'''
This file is part of Mim.
Mim is free software: you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free Software Foundation,
either version 3 of the License, or (at your option) any later version.
Mim is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with Mim.
If not, see <https://www.gnu.org/licenses/>.
'''

canonicalizations = {
    'abolished':	'dissolved, abolished or demolished date',
    'abolishment date':	'dissolved, abolished or demolished date',
    'aboriginal council':	'legislative body',
    'accused':	'participant',
    'active in':	'work location',
    'actor':	'cast member',
    'actress':	'cast member',
    'admin hq':	'headquarters location',
    'administrative centre':	'capital',
    'administrative headquarters':	'capital',
    'administrative territorial entity':	'located in the administrative territorial entity',
    'administrator':	'operator',
    'after':	'replaced by',
    'after':	'replaces',
    'agent':	'participant',
    'air date':	'publication date',
    'alma mater':	'educated at',
    'alumna of':	'educated at',
    'alumni of':	'educated at',
    'alumnus of':	'educated at',
    'amalgamation of':	'has part',
    'appears in':	'present in work',
    'applied to jurisdiction':	'applies to jurisdiction',
    'applies to jurisdiction':	'applies to jurisdiction',
    'applies to territorial jurisdiction':	'applies to jurisdiction',
    'artist':	'performer',
    'artist (non-musical)':	'creator',
    'artistic genre':	'genre',
    'artwork':	'notable work',
    'as of':	'point in time',
    'assembled from':	'has part',
    'assembled out of':	'has part',
    'assembly':	'legislative body',
    'assembly of':	'part of',
    'at time':	'point in time',
    'attendee':	'participant',
    'author':	'author',
    'author':	'lyrics by',
    'author(s)':	'author',
    'authors':	'author',
    'award':	'award received',
    'award received':	'award received',
    'award won':	'award received',
    'awarded':	'award received',
    'awards':	'award received',
    'awards received':	'award received',
    'ballet company':	'production company',
    'based in':	'located in the administrative territorial entity',
    'based in':	'location',
    'basin countries':	'basin country',
    'basin country':	'basin country',
    'battle':	'conflict',
    'bay':	'located in or next to body of water',
    'before was':	'follows',
    'began':	'start time',
    'beginning':	'start time',
    'belligerents':	'participant',
    'belongs to':	'owned by',
    'belongs to jurisdiction':	'applies to jurisdiction',
    'between':	'participant',
    'bibliography':	'notable work',
    'birth city':	'place of birth',
    'birth date':	'date of birth',
    'birth location':	'place of birth',
    'birth place':	'place of birth',
    'birth year':	'date of birth',
    'birthdate':	'date of birth',
    'birthday':	'date of birth',
    'birthplace':	'place of birth',
    'birthyear':	'date of birth',
    'board game publisher':	'publisher',
    'body of water':	'located in or next to body of water',
    'book publisher':	'publisher',
    'born at':	'place of birth',
    'born in':	'place of birth',
    'born on':	'date of birth',
    'branch':	'military branch',
    'bro':	'sibling',
    'broadcast on':	'original broadcaster',
    'broadcasting company':	'production company',
    'brother':	'sibling',
    'brother or sister':	'sibling',
    'builder':	'manufacturer',
    'building date':	'start time',
    'built by':	'manufacturer',
    'candidate':	'participant',
    'capital':	'capital',
    'capital city':	'capital',
    'capital of':	'capital of',
    'capital town':	'capital',
    'cast member':	'cast member',
    'cease date':	'end time',
    'cease operation':	'end time',
    'cease time':	'end time',
    'chairman':	'chairperson',
    'chairperson':	'chairperson',
    'chairwoman':	'chairperson',
    'chancellor':	'head of government',
    'channel':	'original broadcaster',
    'characters':	'characters',
    'chef-lieu':	'capital',
    'chief of state':	'head of state',
    'child':	'child',
    'child of':	'father',
    'child of':	'mother',
    'children':	'child',
    'citizen of':	'country of citizenship',
    'citizenship':	'country of citizenship',
    'city':	'located in the administrative territorial entity',
    'city council':	'legislative body',
    'claimed by':	'territory claimed by',
    'closed':	'end time',
    'closed on':	'dissolved, abolished or demolished date',
    'closure date':	'dissolved, abolished or demolished date',
    'club played for':	'member of sports team',
    'co-founded by':	'founded by',
    'co-founder':	'founded by',
    'college attended':	'educated at',
    'comes after':	'follows',
    'comes before':	'followed by',
    'comes from':	'country of origin',
    'comes from':	'location of formation',
    'commenced on date':	'inception',
    'commencement date':	'inception',
    'commodity':	'product or material produced',
    'competed in':	'participant in',
    'competes in':	'participant in',
    'competitor':	'participant',
    'completed':	'inception',
    'completed in':	'end time',
    'component of':	'part of',
    'composed by':	'composer',
    'composed of':	'has part',
    'composer':	'composer',
    'comprised of':	'has part',
    'computing platform':	'platform',
    'conflict':	'conflict',
    'confluences':	'mouth of the watercourse',
    'consists of':	'has part',
    'consort':	'spouse',
    'constructed':	'inception',
    'construction date':	'inception',
    'contain':	'has part',
    'contained within':	'part of',
    'contains':	'contains administrative territorial entity',
    'contains':	'has part',
    'contains administrative territorial entity':	'contains administrative territorial entity',
    'contestant':	'cast member',
    'continent':	'continent',
    'continued by':	'replaced by',
    'continues from':	'replaces',
    'coo':	'country of origin',
    'council':	'legislative body',
    'country':	'country',
    'country of citizenship':	'country of citizenship',
    'country of jurisdiction':	'applies to jurisdiction',
    'country of origin':	'country of origin',
    'county seat':	'capital',
    'county seat for':	'capital of',
    'county seat of':	'capital of',
    'created':	'inception',
    'created by':	'creator',
    'created from':	'has part',
    'created on date':	'inception',
    'created on language':	'original language of film or TV show',
    'created out of':	'has part',
    'creates':	'product or material produced',
    'creation date':	'inception',
    'creator':	'creator',
    'creators':	'creator',
    'culture':	'ethnic group',
    'dad':	'father',
    'daddy':	'father',
    'date':	'point in time',
    'date commenced':	'inception',
    'date constructed':	'inception',
    'date created':	'inception',
    'date disbanded':	'dissolved, abolished or demolished date',
    'date disestablished':	'dissolved, abolished or demolished date',
    'date dissolved':	'dissolved, abolished or demolished date',
    'date formed':	'inception',
    'date founded':	'inception',
    'date incorporated':	'inception',
    'date of birth':	'date of birth',
    'date of commencement':	'inception',
    'date of creation':	'inception',
    'date of death':	'date of death',
    'date of dissolution':	'dissolved, abolished or demolished date',
    'date of establishment':	'inception',
    'date of foundation':	'inception',
    'date of foundation or creation':	'inception',
    'date of founding':	'inception',
    'date of incorporation':	'inception',
    'date of publication':	'publication date',
    'date of release':	'publication date',
    'date of the end':	'date of death',
    'date published':	'publication date',
    'date released':	'publication date',
    'daughter':	'child',
    'daughter of':	'father',
    'daughter of':	'mother',
    'daughters':	'child',
    'dead':	'date of death',
    'death':	'date of death',
    'death date':	'date of death',
    'death location':	'place of death',
    'death place':	'place of death',
    'deathdate':	'date of death',
    'deathplace':	'place of death',
    'dedication date':	'inception',
    'defunct':	'dissolved, abolished or demolished date',
    'defunct date':	'dissolved, abolished or demolished date',
    'demise date':	'dissolved, abolished or demolished date',
    'demolished':	'dissolved, abolished or demolished date',
    'denomination':	'religion',
    'destroyed in':	'dissolved, abolished or demolished date',
    'developed by':	'developer',
    'developer':	'developer',
    'died in':	'place of death',
    'died on':	'date of death',
    'diet':	'legislative body',
    'directed by':	'director',
    'director':	'director',
    'disbanded':	'dissolved, abolished or demolished date',
    'disbanded on':	'dissolved, abolished or demolished date',
    'disestablished':	'dissolved, abolished or demolished date',
    'dissolution date':	'dissolved, abolished or demolished date',
    'dissolved':	'end time',
    'dissolved on date':	'dissolved, abolished or demolished date',
    'dissolved or abolished':	'dissolved, abolished or demolished date',
    'dissolved, abolished or demolished':	'dissolved, abolished or demolished date',
    'dissolved, abolished or demolished date':	'dissolved, abolished or demolished date',
    'dissolved, abolished, or demolished':	'dissolved, abolished or demolished date',
    'distinct element of':	'instance of',
    'distinct individual member of':	'instance of',
    'distinct member of':	'instance of',
    'district':	'legislative body',
    'district council':	'legislative body',
    'divided into':	'contains administrative territorial entity',
    'divides into':	'contains administrative territorial entity',
    'division':	'league',
    'divorced':	'end time',
    'dob':	'date of birth',
    'dod':	'date of death',
    'dop':	'publication date',
    'drain':	'mouth of the watercourse',
    'during':	'point in time',
    'educated at':	'educated at',
    'education':	'educated at',
    'emperor':	'head of state',
    'employed by':	'employer',
    'employer':	'employer',
    'end date':	'dissolved, abolished or demolished date',
    'end date':	'end time',
    'end time':	'end time',
    'enddate':	'end time',
    'ended':	'dissolved, abolished or demolished date',
    'ending':	'end time',
    'ends':	'end time',
    'endtime':	'end time',
    'environment':	'platform',
    'established':	'inception',
    'established by':	'founded by',
    'established on date':	'inception',
    'establishment date':	'inception',
    'ethnic group':	'ethnic group',
    'ethnicity':	'ethnic group',
    'event location':	'location',
    'event participant':	'participant',
    'executive power headed by':	'head of government',
    'facility operator':	'operator',
    'faculty':	'educated at',
    'faith':	'religion',
    'fall date':	'end time',
    'famous books':	'notable work',
    'famous for':	'notable work',
    'famous works':	'notable work',
    'father':	'father',
    'favorite player':	'influenced by',
    'featured in work':	'present in work',
    'film director':	'director',
    'film genre':	'genre',
    'film producer':	'producer',
    'film script by':	'screenwriter',
    'film starring':	'cast member',
    'film studio':	'production company',
    'final year':	'dissolved, abolished or demolished date',
    'first air channel':	'original broadcaster',
    'first issue':	'inception',
    'first minister':	'head of government',
    'first published':	'publication date',
    'first released':	'publication date',
    'folded':	'dissolved, abolished or demolished date',
    'followed by':	'followed by',
    'follows':	'follows',
    'forefather':	'replaces',
    'forked from':	'separated from',
    'formation':	'inception',
    'formation':	'military branch',
    'formation date':	'inception',
    'formation location':	'location of formation',
    'formed at':	'inception',
    'formed from':	'has part',
    'formed in':	'inception',
    'formed in':	'location of formation',
    'formed on date':	'inception',
    'formed out of':	'has part',
    'foundation':	'inception',
    'foundation date':	'inception',
    'foundation/creation date':	'inception',
    'founded':	'inception',
    'founded by':	'founded by',
    'founded in':	'location of formation',
    'founded on date':	'inception',
    'founder':	'founded by',
    'founders':	'founded by',
    'founding date':	'inception',
    'from':	'location of formation',
    'from':	'start time',
    'from date':	'start time',
    'from narrative':	'present in work',
    'from time':	'start time',
    'from work':	'present in work',
    'game platform':	'platform',
    'garrison':	'headquarters location',
    'genre':	'genre',
    'genre of music':	'genre',
    'geographical region':	'located on terrain feature',
    'government headed by':	'head of government',
    'governor':	'head of government',
    'governor':	'head of state',
    'graduate of':	'educated at',
    'graduated from':	'educated at',
    'happens in':	'located in the administrative territorial entity',
    'has administrative divisions':	'contains administrative territorial entity',
    'has arrondissements':	'contains administrative territorial entity',
    'has as part':	'has part',
    'has boroughs':	'contains administrative territorial entity',
    'has brother':	'sibling',
    'has capital':	'capital',
    'has child':	'child',
    'has children':	'child',
    'has cities':	'contains administrative territorial entity',
    'has class':	'instance of',
    'has component':	'has part',
    'has counties':	'contains administrative territorial entity',
    'has daughter':	'child',
    'has daughters':	'child',
    'has districts':	'contains administrative territorial entity',
    'has father':	'father',
    'has influence':	'influenced by',
    'has ingredient':	'has part',
    'has ingredients':	'has part',
    'has kid':	'child',
    'has kids':	'child',
    'has local government areas':	'contains administrative territorial entity',
    'has mother':	'mother',
    'has municipalities':	'contains administrative territorial entity',
    'has part':	'has part',
    'has product':	'product or material produced',
    'has regions':	'contains administrative territorial entity',
    'has rural cities':	'contains administrative territorial entity',
    'has shires':	'contains administrative territorial entity',
    'has sister':	'sibling',
    'has son':	'child',
    'has sons':	'child',
    'has states':	'contains administrative territorial entity',
    'has superclass':	'subclass of',
    'has towns':	'contains administrative territorial entity',
    'has type':	'instance of',
    'has villages':	'contains administrative territorial entity',
    'has wards':	'contains administrative territorial entity',
    'have part':	'has part',
    'head of government':	'head of government',
    'head of national government':	'head of government',
    'head of state':	'head of state',
    'head office location':	'headquarters location',
    'head quarters':	'headquarters location',
    'headed by':	'chairperson',
    'headquarters':	'headquarters location',
    'headquarters location':	'headquarters location',
    'heir':	'replaced by',
    'higher taxon':	'parent taxon',
    'holding':	'parent organization',
    'holding company':	'parent organization',
    'holds position':	'position held',
    'holonym of':	'has part',
    'home town':	'residence',
    'hometown':	'residence',
    'honorary title':	'award received',
    'honors':	'award received',
    'honours':	'award received',
    'hq':	'headquarters location',
    'hq location':	'headquarters location',
    'husband':	'spouse',
    'husbands':	'spouse',
    'hyponym of':	'subclass of',
    'in':	'located in the administrative territorial entity',
    'in':	'location',
    'in':	'part of',
    'in action':	'conflict',
    'in administrative unit':	'located in the administrative territorial entity',
    'in conflict':	'conflict',
    'in narrative':	'present in work',
    'in the administrative unit':	'located in the administrative territorial entity',
    'in work':	'present in work',
    'inaugurated':	'inception',
    'inception':	'inception',
    'includes':	'has part',
    'includes part':	'has part',
    'incorporated':	'inception',
    'incorporated on date':	'inception',
    'incorporation date':	'inception',
    'indian reservation':	'located in the administrative territorial entity',
    'indigenous council':	'legislative body',
    'influenced by':	'influenced by',
    'informed by':	'influenced by',
    'ingredients':	'has part',
    'initial release':	'publication date',
    'inititated':	'inception',
    'instance of':	'instance of',
    'introduced':	'inception',
    'introduced':	'start time',
    'introduction':	'inception',
    'introduction':	'start time',
    'is a':	'instance of',
    'is a category of':	'subclass of',
    'is a class of':	'subclass of',
    'is a particular':	'instance of',
    'is a specific':	'instance of',
    'is a subtype of':	'subclass of',
    'is a type of':	'subclass of',
    'is a unique':	'instance of',
    'is also a':	'subclass of',
    'is an':	'instance of',
    'is an example of':	'instance of',
    'is an individual':	'instance of',
    'is child of':	'father',
    'is child of':	'mother',
    'is daughter of':	'father',
    'is daughter of':	'mother',
    'is in':	'located on terrain feature',
    'is in':	'location',
    'is in administrative unit':	'located in the administrative territorial entity',
    'is in the administrative region of':	'located in the administrative territorial entity',
    'is in the administrative unit':	'located in the administrative territorial entity',
    'is in the arrondissement of':	'located in the administrative territorial entity',
    'is in the borough of':	'located in the administrative territorial entity',
    'is in the city of':	'located in the administrative territorial entity',
    'is in the commune of':	'located in the administrative territorial entity',
    'is in the county of':	'located in the administrative territorial entity',
    'is in the department of':	'located in the administrative territorial entity',
    'is in the district of':	'located in the administrative territorial entity',
    'is in the indian reservation of':	'located in the administrative territorial entity',
    'is in the indian reserve of':	'located in the administrative territorial entity',
    'is in the local government area of':	'located in the administrative territorial entity',
    'is in the municipality of':	'located in the administrative territorial entity',
    'is in the parish of':	'located in the administrative territorial entity',
    'is in the prefecture of':	'located in the administrative territorial entity',
    'is in the principal area of':	'located in the administrative territorial entity',
    'is in the province of':	'located in the administrative territorial entity',
    'is in the region of':	'located in the administrative territorial entity',
    'is in the rural city of':	'located in the administrative territorial entity',
    'is in the settlement of':	'located in the administrative territorial entity',
    'is in the shire of':	'located in the administrative territorial entity',
    'is in the state of':	'located in the administrative territorial entity',
    'is in the territory of':	'located in the administrative territorial entity',
    'is in the town of':	'located in the administrative territorial entity',
    'is in the village of':	'located in the administrative territorial entity',
    'is in the voivodeship of':	'located in the administrative territorial entity',
    'is in the ward of':	'located in the administrative territorial entity',
    'is located in':	'located in the administrative territorial entity',
    'is necessarily also a':	'subclass of',
    'is on':	'located on terrain feature',
    'is owned by':	'owned by',
    'is shown in':	'present in work',
    'is son of':	'father',
    'is son of':	'mother',
    'is thereby also a':	'subclass of',
    'item operator':	'operator',
    'jila':	'legislative body',
    'jurisdiction':	'applies to jurisdiction',
    'kid':	'child',
    'kids':	'child',
    'kind of music':	'genre',
    'king':	'head of state',
    'known for':	'notable work',
    'label':	'record label',
    'lake':	'located in or next to body of water',
    'land':	'country',
    'language':	'languages spoken, written or signed',
    'language of expression':	'languages spoken, written or signed',
    'language of the original work':	'original language of film or TV show',
    'language official':	'official language',
    'language read':	'languages spoken, written or signed',
    'language signed':	'languages spoken, written or signed',
    'language spoken':	'languages spoken, written or signed',
    'language used':	'languages spoken, written or signed',
    'language written':	'languages spoken, written or signed',
    'language(s) spoken, written or signed':	'languages spoken, written or signed',
    'languages of expression':	'languages spoken, written or signed',
    'languages signed':	'languages spoken, written or signed',
    'languages spoken':	'languages spoken, written or signed',
    'languages spoken, written or signed':	'languages spoken, written or signed',
    'languages spoken, written, or signed':	'languages spoken, written or signed',
    'launch date':	'inception',
    'leader':	'chairperson',
    'leader':	'head of state',
    'league':	'league',
    'left office':	'end time',
    'legislative body':	'legislative body',
    'lga':	'legislative body',
    'life partner':	'spouse',
    'life stance':	'religion',
    'linked to jurisdiction':	'applies to jurisdiction',
    'literary genre':	'genre',
    'literary works':	'notable work',
    'lived in':	'residence',
    'lives in':	'residence',
    'loc (terr)':	'located on terrain feature',
    'loc (water)':	'located in or next to body of water',
    'local government area':	'legislative body',
    'locality':	'located in the administrative territorial entity',
    'located in':	'location',
    'located in administrative unit':	'located in the administrative territorial entity',
    'located in or next to body of water':	'located in or next to body of water',
    'located in the administrative territorial entity':	'located in the administrative territorial entity',
    'located in the administrative unit':	'located in the administrative territorial entity',
    'located in the territorial entity':	'located in the administrative territorial entity',
    'located next to body of water':	'located in or next to body of water',
    'located on body of water':	'located in or next to body of water',
    'located on terrain feature':	'located on terrain feature',
    'location':	'location',
    'location (administrative territorial entity)':	'located in the administrative territorial entity',
    'location (terrain feature)':	'located on terrain feature',
    'location born':	'place of birth',
    'location of birth':	'place of birth',
    'location of death':	'place of death',
    'location of formation':	'location of formation',
    'location of item':	'location',
    'location of narrative':	'narrative location',
    'location of work':	'work location',
    'lyracist':	'lyrics by',
    'lyricist':	'lyrics by',
    'lyrics by':	'lyrics by',
    'made by':	'creator',
    'made by':	'manufacturer',
    'major works':	'notable work',
    'maker':	'manufacturer',
    'maker of':	'product or material produced',
    'makes':	'product or material produced',
    'mam':	'mother',
    'managed by':	'operator',
    'manufactured by':	'manufacturer',
    'manufacturer':	'manufacturer',
    'manufacturer of':	'product or material produced',
    'manufactures':	'product or material produced',
    'marriage partner':	'spouse',
    'married':	'spouse',
    'married to':	'spouse',
    'marry':	'spouse',
    'material produced':	'product or material produced',
    'mayor':	'head of government',
    'medals':	'award received',
    'mediatised to':	'replaced by',
    'member of':	'instance of',
    'member of':	'member of',
    'member of':	'member of political party',
    'member of party':	'member of political party',
    'member of political party':	'member of political party',
    'member of sports team':	'member of sports team',
    'member of team':	'member of sports team',
    'merged into':	'part of',
    'merged with':	'part of',
    'meronym of':	'part of',
    'mfr':	'manufacturer',
    'military branch':	'military branch',
    'mom':	'mother',
    'monarch':	'head of state',
    'mother':	'mother',
    'motion picture studio':	'production company',
    'mouth of the watercourse':	'mouth of the watercourse',
    'moveable object location':	'location',
    'movie director':	'director',
    'movie studio':	'production company',
    'mum':	'mother',
    'municipal council':	'legislative body',
    'music by':	'composer',
    'music genre':	'genre',
    'musical artist':	'performer',
    'musical score by':	'composer',
    'musician':	'performer',
    'narrative location':	'narrative location',
    'narrative set in':	'narrative location',
    'national of':	'country of citizenship',
    'nationality':	'country of citizenship',
    'neighborhood':	'location',
    'network':	'original broadcaster',
    'next is':	'followed by',
    'next job holder':	'replaced by',
    'next to lake':	'located in or next to body of water',
    'non-type member of':	'instance of',
    'not a type but is instance of':	'instance of',
    'notable books':	'notable work',
    'notable work':	'notable work',
    'occurrence of':	'instance of',
    'ocean':	'located in or next to body of water',
    'of jurisdiction':	'applies to jurisdiction',
    'of team':	'member of sports team',
    'office held':	'position held',
    'official language':	'official language',
    'on':	'located on terrain feature',
    'on bay':	'located in or next to body of water',
    'on coast of':	'located in or next to body of water',
    'on geographical feature':	'located on terrain feature',
    'on harbour':	'located in or next to body of water',
    'on lake':	'located in or next to body of water',
    'on natural feature':	'located on terrain feature',
    'on river':	'located in or next to body of water',
    'on shore of':	'located in or next to body of water',
    'on the coast of':	'located in or next to body of water',
    'on the shore of':	'located in or next to body of water',
    'operated by':	'operator',
    'operator':	'operator',
    'origin (country)':	'country of origin',
    'original air channel':	'original broadcaster',
    'original broadcaster':	'original broadcaster',
    'original channel':	'original broadcaster',
    'original language':	'original language of film or TV show',
    'original language of film or TV show':	'original language of film or TV show',
    'original network':	'original broadcaster',
    'originates':	'country of origin',
    'originates from':	'location of formation',
    'outflow':	'mouth of the watercourse',
    'outlet':	'mouth of the watercourse',
    'output':	'product or material produced',
    'owned by':	'owned by',
    'owned by (company or organisation)':	'parent organization',
    'owned by (company or organization)':	'parent organization',
    'owner':	'owned by',
    'owners':	'owned by',
    'painter':	'creator',
    'painters':	'creator',
    'parent':	'father',
    'parent':	'mother',
    'parent agency':	'parent organization',
    'parent company':	'parent organization',
    'parent company of':	'subsidiary',
    'parent of':	'child',
    'parent organisation':	'parent organization',
    'parent organization':	'parent organization',
    'parent taxon':	'parent taxon',
    'parent unit':	'parent organization',
    'parliament':	'legislative body',
    'part of':	'parent organization',
    'part of':	'part of',
    'part of series':	'part of the series',
    'part of team':	'member of sports team',
    'part of the series':	'part of the series',
    'part of-property':	'part of',
    'participant':	'participant',
    'participant in':	'participant in',
    'participant in conflict':	'conflict',
    'participant in':	'participant in',
    'participant in event':	'participant in',
    'participant of':	'participant in',
    'participant of event':	'participant in',
    'participants':	'participant',
    'participated in':	'participant in',
    'participated in conflict':	'conflict',
    'partner':	'spouse',
    'partner city':	'twinned administrative body',
    'partner town':	'twinned administrative body',
    'partners':	'spouse',
    'parts':	'has part',
    'party':	'member of political party',
    'party':	'participant',
    'party membership':	'member of political party',
    'people':	'ethnic group',
    'performer':	'performer',
    'perpetrator':	'participant',
    'place held':	'location',
    'place of activity':	'work location',
    'place of birth':	'place of birth',
    'place of death':	'place of death',
    'place of formation':	'location of formation',
    'place of foundation':	'location of formation',
    'place of incorporation':	'location of formation',
    'place of origin':	'country of origin',
    'place of residence':	'residence',
    'place of work':	'work location',
    'platform':	'platform',
    'platforms':	'platform',
    'played by':	'performer',
    'played for':	'member of sports team',
    'player':	'participant',
    'player of':	'member of sports team',
    'plays for':	'member of sports team',
    'pob':	'place of birth',
    'pod':	'place of death',
    'point in time':	'point in time',
    'political office held':	'position held',
    'political party':	'member of political party',
    'political seat':	'position held',
    'portrayed by':	'performer',
    'position held':	'position held',
    'position occupied':	'position held',
    'preceded by':	'follows',
    'preceded by':	'replaces',
    'precedes':	'followed by',
    'preceeds':	'followed by',
    'predecessor':	'follows',
    'predecessor':	'replaces',
    'premier':	'head of government',
    'prequel is':	'follows',
    'prequel of':	'followed by',
    'present in work':	'present in work',
    'president':	'chairperson',
    'president':	'head of state',
    'previous is':	'follows',
    'previous job holder':	'replaces',
    'prime minister':	'head of government',
    'principal place':	'capital',
    'principle office':	'headquarters location',
    'prize awarded':	'award received',
    'prize received':	'award received',
    'producer':	'producer',
    'producer (of product)':	'manufacturer',
    'producer of':	'product or material produced',
    'produces':	'product or material produced',
    'product':	'product or material produced',
    'product of':	'manufacturer',
    'product or material produced':	'product or material produced',
    'production company':	'production company',
    'production house':	'production company',
    'products':	'product or material produced',
    'provenance':	'owned by',
    'pubdate':	'publication date',
    'public office':	'position held',
    'publication':	'publication date',
    'publication date':	'publication date',
    'publication time':	'publication date',
    'published':	'publication date',
    'published by':	'publisher',
    'published on':	'platform',
    'publisher':	'publisher',
    'publishing house':	'publisher',
    'queen':	'head of state',
    'radio network':	'original broadcaster',
    'radio station':	'original broadcaster',
    'rdf:type':	'instance of',
    'rdfs:subclassof':	'subclass of',
    'recognition title':	'award received',
    'record label':	'record label',
    'record producer':	'producer',
    'region':	'located in the administrative territorial entity',
    'region':	'location',
    'release date':	'publication date',
    'released':	'publication date',
    'religion':	'religion',
    'religious affiliation':	'religion',
    'replaced':	'replaces',
    'replaced by':	'replaced by',
    'replaces':	'replaces',
    'representative body':	'legislative body',
    'representative work':	'notable work',
    'residence':	'residence',
    'resident in':	'residence',
    'results in':	'product or material produced',
    'river mouth':	'mouth of the watercourse',
    'role model':	'influenced by',
    'runtime':	'platform',
    'rural council':	'legislative body',
    'schism from':	'separated from',
    'school attended':	'educated at',
    'screenplay by':	'screenwriter',
    'screenwriter':	'screenwriter',
    'scriptwriter':	'screenwriter',
    'sculptor':	'creator',
    'sculptors':	'creator',
    'sea':	'located in or next to body of water',
    'seat':	'headquarters location',
    'seceded from':	'separated from',
    'second language':	'languages spoken, written or signed',
    'section of':	'part of',
    'separated from':	'separated from',
    'sequel is':	'followed by',
    'sequel of':	'follows',
    'service branch':	'military branch',
    'service operator':	'operator',
    'set in location':	'narrative location',
    'set of':	'has part',
    'setting location':	'narrative location',
    'shareholder':	'owned by',
    'shareholders':	'owned by',
    'sib':	'sibling',
    'sibling':	'sibling',
    'signed language':	'languages spoken, written or signed',
    'significance':	'notable work',
    'significant works':	'notable work',
    'signs language':	'languages spoken, written or signed',
    'since':	'start time',
    'sis':	'sibling',
    'sister':	'sibling',
    'sister city':	'twinned administrative body',
    'sister or brother':	'sibling',
    'sister town':	'twinned administrative body',
    'software publisher':	'publisher',
    'son':	'child',
    'son of':	'father',
    'son of':	'mother',
    'songwriter':	'composer',
    'sons':	'child',
    'source location of group/organisation':	'location of formation',
    'sovereign state':	'country',
    'speaks language':	'languages spoken, written or signed',
    'split from':	'follows',
    'spoke language':	'languages spoken, written or signed',
    'sports league':	'league',
    'spouse':	'spouse',
    'spouses':	'spouse',
    'starring':	'cast member',
    'start date':	'inception',
    'start date':	'start time',
    'start time':	'start time',
    'started in':	'start time',
    'starting':	'start time',
    'starttime':	'start time',
    'state':	'country',
    'state':	'located in the administrative territorial entity',
    'state headed by':	'head of state',
    'stockholder':	'owned by',
    'stockholders':	'owned by',
    'studied at':	'educated at',
    'studio':	'production company',
    'subassembly of':	'part of',
    'subcategory of':	'subclass of',
    'subclass of':	'subclass of',
    'subdivided into':	'contains administrative territorial entity',
    'subject of (country)':	'country of citizenship',
    'subset of':	'subclass of',
    'subsidiary':	'subsidiary',
    'subsidiary company':	'subsidiary',
    'subsidiary entities':	'subsidiary',
    'subsidiary of':	'parent organization',
    'subsystem of':	'part of',
    'subtype of':	'subclass of',
    'succeded by':	'followed by',
    'succeeded by':	'replaced by',
    'succeeds':	'replaces',
    'succeeds to':	'follows',
    'successor':	'followed by',
    'successor':	'replaced by',
    'superior formation':	'parent organization',
    'superseded by':	'replaced by',
    'supersedes':	'replaces',
    'suspect':	'participant',
    'system of':	'part of',
    'takes part':	'participant in',
    'takes place in':	'located on terrain feature',
    'taxon parent':	'parent taxon',
    'team':	'member of sports team',
    'team played for':	'member of sports team',
    'teams played for':	'member of sports team',
    'tehsil':	'legislative body',
    'teleplay by':	'screenwriter',
    'television channel':	'original broadcaster',
    'terrain feature':	'located on terrain feature',
    'territory claimed by':	'territory claimed by',
    'theater (military)':	'conflict',
    'theater company':	'production company',
    'theatre (military)':	'conflict',
    'theatre company':	'production company',
    'theatrical troupe':	'production company',
    'till':	'end time',
    'time':	'point in time',
    'time abolished':	'dissolved, abolished or demolished date',
    'time dissolved':	'dissolved, abolished or demolished date',
    'time of abolishment':	'dissolved, abolished or demolished date',
    'time of dissolution':	'dissolved, abolished or demolished date',
    'time of event':	'point in time',
    'time of foundation or creation':	'inception',
    'time of inception':	'inception',
    'time of publication':	'publication date',
    'to':	'end time',
    'to time':	'end time',
    'took part':	'participant in',
    'took part in':	'participant in',
    'town':	'located in the administrative territorial entity',
    'tributary of':	'mouth of the watercourse',
    'tv channel':	'original broadcaster',
    'twin cities':	'twinned administrative body',
    'twin city':	'twinned administrative body',
    'twin town':	'twinned administrative body',
    'twinned administrative body':	'twinned administrative body',
    'type':	'instance of',
    'type of':	'subclass of',
    'type of film':	'genre',
    'type of music':	'genre',
    'unemployment rate':	'unemployment rate',
    'uninstantiable instance of':	'instance of',
    'unique individual of':	'instance of',
    'unitary element of class':	'instance of',
    'university attended':	'educated at',
    'unsubclassable example of':	'instance of',
    'unsubclassifiable member of':	'instance of',
    'unsubtypable particular':	'instance of',
    'until':	'end time',
    'used language':	'languages spoken, written or signed',
    'user':	'operator',
    'uses language':	'languages spoken, written or signed',
    'valid in jurisdiction':	'applies to jurisdiction',
    'venue':	'location',
    'victim':	'participant',
    'video game publisher':	'publisher',
    'war':	'conflict',
    'watercourse drain':	'mouth of the watercourse',
    'watercourse ends in':	'mouth of the watercourse',
    'watercourse outflow':	'mouth of the watercourse',
    'wed':	'spouse',
    'wedded to':	'spouse',
    'when':	'point in time',
    'where':	'location',
    'whose instances are among':	'subclass of',
    'whose instances ⊆ those of':	'subclass of',
    'wife':	'spouse',
    'win':	'award received',
    'winner of':	'award received',
    'within':	'part of',
    'wives':	'spouse',
    'words by':	'lyrics by',
    'work':	'notable work',
    'work location':	'work location',
    'work produced':	'product or material produced',
    'worked at':	'employer',
    'worked for':	'employer',
    'working for':	'employer',
    'working place':	'employer',
    'workplace':	'employer',
    'workplace':	'work location',
    'works':	'notable work',
    'works at':	'employer',
    'works for':	'employer',
    'wound up on date':	'dissolved, abolished or demolished date',
    'writer':	'author',
    'writer (of screenplays)':	'screenwriter',
    'writer (of song lyrics)':	'lyrics by',
    'writer(s)':	'author',
    'writers':	'author',
    'writes language':	'languages spoken, written or signed',
    'written by':	'author',
    'written by':	'composer',
    'written by':	'screenwriter',
    'written on date':	'inception',
    'wrote language':	'languages spoken, written or signed',
    'year':	'point in time',
    'year commenced':	'inception',
    'year created':	'inception',
    'year established':	'inception',
    'year founded':	'inception',
    'year incorporated':	'inception',
    'year of birth':	'date of birth',
    'year of death':	'date of death',
    'year of publication':	'publication date',
    'year written':	'inception',
    'zila':	'legislative body',
    '⊂':	'subclass of',
    '⊆':	'subclass of',
}

# TODO: Might also try just using "ADP", "VERB ADP", "NOUN ADP", "PART", etc. instead and compare with this
filter_patterns = {
    # 'ARGUMENT DET VERB ADJ': '',
    'ARGUMENT ADP NOUN': (1,2), #'ADP',
    'ARGUMENT ADP ENTITY': (1,2), #'ADP',
    # 'ARGUMENT DET VERB NOUN': '',
    'ARGUMENT PART VERB': (1,2), #'PART',
    # 'ARGUMENT DET AUX VERB': '',
    'ARGUMENT ADP ARGUMENT': (1,2), #'ADP',
    'ARGUMENT ADP NOUN NOUN': (1,2), #'ADP',
    'ARGUMENT VERB ADP ARGUMENT': (1,3), #'VERB ADP',
    'ARGUMENT ADJ ADP ARGUMENT': (1,3), #'ADJ ADP',
    'PROPN ADP ENTITY': (1,2), #'ADP',
    'ARGUMENT DET VERB ADP ARGUMENT': (2,4), #'VERB ADP',
    'ARGUMENT ADP ADJ NOUN': (1,2), #'ADP',
    'ARGUMENT ADP DET NOUN': (1,2), #'ADP',
    # 'ARGUMENT DET VERB ENTITY': '',
    'ARGUMENT DET AUX VERB ADP ARGUMENT': (3,5), #'VERB ADP',
    # 'PROPN DET VERB ADJ': '',
    'ARGUMENT DET VERB ADP ENTITY': (2,4), #'VERB ADP',
    'ARGUMENT ADP ENTITY NOUN': (1,2), #'ADP',
    # 'ARGUMENT DET VERB ADP DET NOUN': '',
    'ARGUMENT VERB ADP ENTITY': (1,3), #'VERB ADP',
    'ARGUMENT VERB ARGUMENT': (1,2), #'VERB',
    'PROPN PART VERB': (1,2), #'PART',
    'VERB ADP ENTITY': (1,2), #'ADP',
    'ARGUMENT DET VERB ADP NOUN': (2,4), #'VERB ADP',
    # 'VERB DET VERB ADJ': '',
    # 'ARGUMENT DET AUX VERB ADV': '',
    # 'ARGUMENT DET VERB ADJ NOUN': '',
    # 'ARGUMENT DET VERB VERB': '',
    # 'ARGUMENT DET AUX ADJ': '',
    'ARGUMENT DET AUX VERB ADP ENTITY': (3,5), #'VERB ADP',
    'ADP DET VERB ADJ': (2,3), #'VERB',
    # 'ARGUMENT DET VERB ENTITY NOUN': '',
    # 'ARGUMENT DET VERB ADJ ADJ': '',
    'ARGUMENT DET VERB ADJ ADP ARGUMENT': (3,5), #'ADJ ADP',
    'ARGUMENT DET VERB ADP PROPN': (2,4), #'VERB ADP',
    'ARGUMENT DET AUX VERB ARGUMENT': (3,4), #'VERB',
    'ARGUMENT ADP DET ENTITY': (1,2), #'ADP',
    # 'ARGUMENT DET VERB ADV ADJ': '',
    # 'ARGUMENT DET VERB DET NOUN': '',
    'ARGUMENT ADP ADJ': (1,2), #'ADP',
    'VERB ADP NOUN': (1,2), #'ADP',
    'ARGUMENT DET AUX VERB ADP NOUN': (3, 5), #'VERB ADP',
    'ARGUMENT DET VERB ARGUMENT': (2,3), #'VERB',
    # 'ARGUMENT DET VERB PROPN': '',
    'ARGUMENT DET AUX VERB ADP DET NOUN': (3,5), #'VERB ADP',
    # 'ARGUMENT DET AUX VERB ADP': '',
    'ARGUMENT ADP DET NOUN ADP ARGUMENT': (3,5), #'NOUN ADP',
    'ARGUMENT VERB ADP NOUN': (1,3), #'VERB ADP',
    'ARGUMENT ADP DET ADJ NOUN': (1,2), #'ADP'
}

project_patterns = {
    'NOUN ADP ARGUMENT': (0,1), #'NOUN',
    'NOUN NOUN ADP ARGUMENT': (0,2), #'NOUN NOUN',
    'DET NOUN ADP ARGUMENT': (1,2), #'NOUN',
    'ADV AUX ARGUMENT': (0,1), #'ADV',
    'ADJ NOUN ADP ARGUMENT': (0,2), #'ADJ NOUN',
    'NOUN ADP PROPN': (0,1), #'NOUN',
    'NOUN VERB ADP ARGUMENT': (1,3), #'VERB ADP',
    'NOUN ADP NOUN': (0,1), #'NOUN',
    'VERB NOUN ADP ARGUMENT': (0,2), #'VERB NOUN',
    'ENTITY ADP ARGUMENT': (0,1), #'ENTITY',
    'ENTITY NOUN ADP ARGUMENT': (0,2), #'ENTITY NOUN',
    'VERB ADP ARGUMENT': (0,1), #'VERB',
    'NOUN ADP NOUN ADP ARGUMENT': (0,3), #'NOUN ADP NOUN',
    'DET SPACE NOUN ADP ARGUMENT': (2,3), #'NOUN',

    # The below is a special case of forms such as 'when did @@1@@ die'. Should maybe handle by
    # using VERB and then appending 'in' if ADV is 'where' or 'on' in ADV is 'when'.
    'ADV AUX ARGUMENT VERB': (3,4), #'VERB',
    'PRON VERB ARGUMENT': (1,2), #'VERB',
    # 'ADJ ADP ARGUMENT': '',
    # 'ADJ ARGUMENT': '',
    'NOUN DET VERB ARGUMENT': (2,3), #'VERB',
    'PRON VERB PROPN': (1,2), #'VERB',
    'NOUN ADP SPACE ARGUMENT': (0,1), #'NOUN',
    'NOUN VERB ADP ADP ARGUMENT': (1,3), #'VERB ADP',
    'NOUN DET ARGUMENT VERB': (3,4), #'VERB',
    'DET ADJ NOUN ADP ARGUMENT': (1,3), #'ADJ NOUN',
    'NOUN NOUN NOUN ADP ARGUMENT': (0,3), #'NOUN NOUN NOUN',
    'NOUN DET VERB ADP ARGUMENT': (2,4), #'VERB ADP',
    # 'ADJ PROPN': '',

    # Another special case, might work best if it was a concatenation of the NOUN and the VERB.
    'NOUN ARGUMENT VERB': (2,3), #'VERB'
}

